version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432/tcp
#  redis:
#    restart: always
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    command: ["redis-server", "--appendonly", "yes"]
#    hostname: redis

  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ACCOUNT_SID=${ACCOUNT_SID}
      - API_KEY=${API_KEY}
      - API_KEY_SECRET=${API_KEY_SECRET}
      - APP_SID=${APP_SID}
      - PUSH_CREDENTIAL_SID=${PUSH_CREDENTIAL_SID}
      - REDIS_URI=${REDIS_URI}r
      - REDIS_URL=${REDIS_URL}
      - DEBUG=${DEBUG}
      - AUTHY_API_KEY=${AUTHY_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
              ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
#      - redis
#    links:
#      - redis
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
