# Generated by Django 2.1.9 on 2019-07-15 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=30)),
                ("content", models.CharField(max_length=2000)),
                ("picture_url", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserReadStories",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField()),
                ("interested", models.BooleanField()),
                ("modified_at", models.DateTimeField()),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stories.Story"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="story",
            name="users",
            field=models.ManyToManyField(
                through="stories.UserReadStories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
