# Generated by Django 5.2.17 on 2026-08-16 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20190821_1308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('title', 'live_date'), name='unique_story_title_per_day'),
        ),
        migrations.AddConstraint(
            model_name='userreadstory',
            constraint=models.UniqueConstraint(fields=('user', 'story'), name='unique_user_read_story'),
        ),
    ]
