# Generated by Django 2.1.9 on 2019-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20190716_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='live_date',
            field=models.DateField(default=None),
        ),
    ]
