# Generated by Django 2.1.9 on 2019-07-23 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('ONLINE', 'online'), ('LOOKING', 'looking_for_match'), ('WAITING', 'waiting_for_match'), ('MATCHED', 'matched'), ('OFFLINE', 'offline')], default='OFFLINE', max_length=24)),
                ('role', models.CharField(choices=[('CALLER', 'caller'), ('RECEIVER', 'receiver')], default=None, max_length=24)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
