# Generated by Django 2.1.9 on 2019-07-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingroom',
            name='role',
            field=models.CharField(choices=[('UNASSIGNED', 'unassigned'), ('CALLER', 'caller'), ('RECEIVER', 'receiver')], default=None, max_length=24),
        ),
    ]
