#!/usr/bin/env python
# coding: utf-8

# In[1]:

import random

# print(random.randint(0, 1))

# In[2]:


database = [{'user': {'detail': {'date_joined': '2019-09-01T09:45:53.933Z',
                                 'date_of_birth': '1940-12-02',
                                 'email': 'caller@jumanji.com',
                                 'first_name': '',
                                 'id': '13912646-e408-4272-8e74-b2a0b8968b2d',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:53.934Z',
                                 'date_of_birth': '1926-03-14',
                                 'email': 'receiver@jumanji.com',
                                 'first_name': '',
                                 'id': '62c78291-2651-4b97-8c50-0f02a3f71037',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:53.935Z',
                                 'date_of_birth': '1969-08-17',
                                 'email': '2zdwzl@jumanji-hq.com',
                                 'first_name': '',
                                 'id': 'e08fbd62-db13-4c7a-baeb-d41695bff62a',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:54.064Z',
                                 'date_of_birth': '1954-05-17',
                                 'email': 'fd3sm6@jumanji-hq.com',
                                 'first_name': '',
                                 'id': 'b1d695c9-c4c1-4aaf-a039-52f84200f142',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:54.122Z',
                                 'date_of_birth': '1941-08-08',
                                 'email': 'sco162@jumanji-hq.com',
                                 'first_name': '',
                                 'id': '2e4195e6-0d16-4d0a-8e41-4de7b5df36ad',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:54.182Z',
                                 'date_of_birth': '1923-11-28',
                                 'email': 'cg2egn@jumanji-hq.com',
                                 'first_name': '',
                                 'id': 'b4151b33-7e3e-4aa1-928f-822f73f7f017',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:54.242Z',
                                 'date_of_birth': '1965-12-18',
                                 'email': 'vkvmim@jumanji-hq.com',
                                 'first_name': '',
                                 'id': '858b19df-fd4a-4f1f-9f97-ca47491c812a',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:54.302Z',
                                 'date_of_birth': '1953-05-15',
                                 'email': 'ss7oyz@jumanji-hq.com',
                                 'first_name': '',
                                 'id': 'c3042328-87a7-43b2-b868-ed1703845179',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:54.363Z',
                                 'date_of_birth': '1945-10-21',
                                 'email': 'vgsz01@jumanji-hq.com',
                                 'first_name': '',
                                 'id': 'c2392268-7073-47f2-a804-e91eccdee437',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:54.422Z',
                                 'date_of_birth': '1946-08-27',
                                 'email': 's0gyk3@jumanji-hq.com',
                                 'first_name': '',
                                 'id': '4d68937b-b5c2-4656-a326-acb4a42a4ed3',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}},
            {'user': {'detail': {'date_joined': '2019-09-01T09:45:54.482Z',
                                 'date_of_birth': '1949-09-18',
                                 'email': 'i8xrw0@jumanji-hq.com',
                                 'first_name': '',
                                 'id': 'fb6a038b-741b-46dc-a7f7-bccd661d2015',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': random.randint(0, 1),
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}}]

# In[3]:


user_temp = {'user': {'detail': {'date_joined': '2019-09-01T09:45:53.999Z',
                                 'date_of_birth': '1941-03-18',
                                 'email': 'gu4w23@jumanji-hq.com',
                                 'first_name': '',
                                 'id': '0d2fa111-c05c-4f21-bf7e-1a7a2d3c41eb',
                                 'is_active': True,
                                 'last_login': None,
                                 'last_name': ''},
                      'stories': [{'content': 'Content for  x6s6kg',
                                   'created_at': '2019-09-01T09:45:53.998Z',
                                   'id': 2,
                                   'interested': True,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:53.998Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title x6s6kg'},
                                  {'content': 'Content for  4l33j3',
                                   'created_at': '2019-09-01T09:45:54.062Z',
                                   'id': 3,
                                   'interested': True,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.062Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 4l33j3'},
                                  {'content': 'Content for  dbxq8h',
                                   'created_at': '2019-09-01T09:45:54.121Z',
                                   'id': 4,
                                   'interested': False,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.121Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dbxq8h'},
                                  {'content': 'Content for  zdcb0c',
                                   'created_at': '2019-09-01T09:45:54.181Z',
                                   'id': 5,
                                   'interested': False,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.181Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title zdcb0c'},
                                  {'content': 'Content for  fjygqp',
                                   'created_at': '2019-09-01T09:45:54.241Z',
                                   'id': 6,
                                   'interested': True,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.241Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title fjygqp'},
                                  {'content': 'Content for  qw4hoi',
                                   'created_at': '2019-09-01T09:45:54.301Z',
                                   'id': 7,
                                   'interested': False,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.301Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title qw4hoi'},
                                  {'content': 'Content for  dpczk8',
                                   'created_at': '2019-09-01T09:45:54.363Z',
                                   'id': 8,
                                   'interested': False,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.363Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dpczk8'},
                                  {'content': 'Content for  37ezvf',
                                   'created_at': '2019-09-01T09:45:54.422Z',
                                   'id': 9,
                                   'interested': False,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.422Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 37ezvf'},
                                  {'content': 'Content for  dd9kb6',
                                   'created_at': '2019-09-01T09:45:54.482Z',
                                   'id': 10,
                                   'interested': True,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.482Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title dd9kb6'},
                                  {'content': 'Content for  1opkj4',
                                   'created_at': '2019-09-01T09:45:54.542Z',
                                   'id': 11,
                                   'interested': False,
                                   'live_date': '2019-09-01',
                                   'modified_at': '2019-09-01T09:45:54.542Z',
                                   'picture_url': 'https://loremflickr.com/640/480/beach,holiday,old/all',
                                   'title': 'Title 1opkj4'}]}}

# In[10]:


user_likes = list()
for j in range(len(user_temp['user']['stories'])):

    if user_temp['user']['stories'][j]['interested']:
        user_likes.append(user_temp['user']['stories'][j]['id'])
    else:
        continue

# print(user_likes)

# In[16]:


coeff = 0
id_match = None
story_match = None

for i in range(len(database)):

    temp_likes = list()
    for j in range(len(database[i]['user']['stories'])):
        if database[i]['user']['stories'][j]['interested']:
            temp_likes.append(database[i]['user']['stories'][j]['id'])
        else:
            continue

    # print(temp_likes)
    intersection = list(set(temp_likes) & set(user_likes))
    union = list(set(temp_likes + user_likes))

    coeff_new = len(intersection) / len(union)
    # print(coeff_new)
    if (coeff_new > coeff):
        id_match = database[i]['user']['detail']['id']
        story_match = random.sample(intersection, 1)
        coeff = coeff_new
        user_no = i

# In[17]:


print(id_match)

# In[19]:


print(story_match[0])

# In[14]:


# print(coeff)

# In[ ]:


# In[ ]:




