# Generated by Django 2.1.9 on 2019-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20190806_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchactivity',
            name='caller_access_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='matchactivity',
            name='receiver_access_token',
            field=models.CharField(max_length=1024),
        ),
    ]
