# Generated by Django 2.1.9 on 2019-08-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20190820_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='caller_access_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='match',
            name='receiver_access_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='room',
            name='access_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='roomactivity',
            name='access_token',
            field=models.CharField(max_length=1024),
        ),
    ]
